        <div class="pages-inner">
			
			<div class="container-inner">
    			<!--- Section starts here --->
    			<div class="tandc-container">
    			    <div class="tandc-header mobile">StayOne and Cotel Terms & Conditions</div>
    			    <div class="tandc-links">
    			        <div class="tandc-item-link"><a class="active" href="#">Terms</a></div>
    			        <div class="tandc-item-link"><a href="#">Privacy</a></div>
    			    </div>
    			    <div class="tandc-content">
    			        <div class="tandc-header web">StayOne and Cotel Terms & Conditions</div>
    			        <div class="tandc-subhead">StayOne Terms & Conditions</div>
    			        <div class="tandc-subhead">Updated November 2021</div>
    			        <div class="tandc-note">
    			            This StayOne Terms and Conditions (T & C) governs your use of the website/platform for the StayOne property and reservation and is entered into by Small Small Technology Limited (“SST”) and yourself (“you”). The documents, data, information and other materials (collectively the “Material(s)”) contained on the Company’s website and platform (the “Platform”) are provided by the Company, exclusively for non-commercial, individual use by prospective and confirmed Company guests to inquire about or make reservations and related services and for no other purpose (collectively, “Authorized Users”).BY ACCESSING, USING, VIEWING, TRANSMITTING, CACHING OR STORING THIS SITE OR ANY OF ITS SERVICES, FUNCTIONS, MATERIALS, OR CONTENTS, YOU SHALL BE DEEMED TO HAVE AGREED TO EACH AND ALL THE TERMS, CONDITIONS, AND NOTICES IN THIS AGREEMENT WITHOUT MODIFICATION. If you are not an Authorized User, and if you do not agree to the terms of this Agreement, you may not use this Site or download any Materials from it. The Company, in its sole and absolute discretion, reserves the right to change the terms, conditions, and notices under which the Materials and the Site are offered at any time without notice and, unless otherwise indicated, such changes will become effective immediately; therefore, please check these terms periodically for changes. Your continued use of the Site following the posting of changes to this Agreement will mean you accept those changes.
    			        </div>
    			        
    			        <div class="tandc-subhead">Reservation Policy and Payment</div>
    			        <div class="tandc-note">
    			            For any reservation to be valid, reservation can only be held for 48 hours; after which it is cancelled automatically. A deposit of 50% of the total accommodation bill shall be required to make a valid reservation. A StayOne subscriber may cancel with sufficient notice. Payments must be made before check – in Failure to pay prescribed fees/dues as at when due will attract penalties such as cessation or refusal of service delivery to StayOne subscriber where applicable. In addition, any other privilege associated with residing in the StayOne may be withdrawn from any StayOne subscriber who fails to meet his/her financial obligations
    			        </div>
    			        
    			        <div class="tandc-subhead">Cancellation and change of booking date:</div>
    			        <div class="tandc-note">
    			            Any cancellation or modification of a booking can only be effected by the StayOne Subscriber providing a written notification of the cancellation or modification to StayOne. The non-payment of rental balances results in automatic cancellation.<br />
                            Should the Guest for whatever reason cancel the booking, they will have the right to reimbursement of all money paid subject to the deduction of cancellation charges being 30% of the total rental price if cancellation is made 14 days prior to the guest checking in. Changes to booking dates or properties are subject to availability. Each booking change shall incur a service fee of 10% to be paid at the time of confirming the said changes. If we cancel a confirmed booking, we shall do our utmost to find a replacement property acceptable to the Guest, or refund any monies paid on unused rental. The Guest agrees and acknowledges that in this event, StayOne liability for damages will be limited to the amount of unused rental, based on a pro rata calculation of unused rental days. Should a property become unserviceable prior to the arrival of a Guest, We will do our best to find a suitable replacement property of an equal standard. In the event of a more expensive property being selected, the Guest will have the choice of paying the difference or receiving a full refund of monies paid. Cancellations cannot be made once the guest has checked-in and all booking payments are non-refundable after the guest has checked-in.
    			        </div>
    			        
    			        <div class="tandc-subhead">Check- in and Check Out</div>
    			        <div class="tandc-note">
    			            All properties are usually available for occupation after 12:00 noon on the day of arrival. All properties must be vacated by 12:00 noon on the day of departure. If there is any delay in vacating the property beyond the agreed time a full day’s rental is charged to you. Please hand over key to the steward on duty when checking
    			        </div>
    			        
    			        <div class="tandc-subhead">Security Deposit and Property Damage:</div>
    			        <div class="tandc-note">
    			            All security deposits are fully refundable PROVIDED there are no damages to the booked StayOne property by you or your associates. A 50% security deposit must be paid before check – in. In the event that a guest damages an item, multiple items or damages the property, a guest forfeits the caution or security deposit paid and the guest is liable to cover cost of up to ₦500,000 damages equating to the cost of replacing the damaged item(s) or damaged property as stipulated by StayOne. The security deposit shall be refunded within 72hrs of you or your guest’s departure. We have the authority to withhold or deduct monies from the security deposit or credit card to remedy any damage, excess cleaning, missing items, excess utilities caused by the Guest or to send an invoice for such monies to the Guest by email for immediate payment. You may not remove any of the furniture or effects from the properties and will be liable for any furniture or effects damaged or missing from the properties. Furniture must be returned to its original position. Our representatives and subcontractors have the right of access to the property at any time, with due regard to your convenience, for the purpose of inspection of the properties and to carry out any essential repair or maintenance work.
    			        </div>
    			        
    			        <div class="tandc-subhead">No Unaccredited Visitor/Guest On The Property</div>
    			        <div class="tandc-note">
    			            All accommodation must only be used for private/residential use only. Not to sub-let or host unauthorized guests or visitors for a period beyond a week or otherwise part with possession of the Property without the written consent of SST. A violation of this rule would incur a punitive cost of One Hundred Thousand Naira Only (N100,000.00). No functions, get-togethers or gatherings where occupants of neighbouring apartments might be disturbed may be conducted at the property under any circumstances unless agreed by StayOne in writing before such an event or function. Admission of guests without approval will result in automatic termination of booking and you being required to vacate the property immediately without refund unless already agreed in writing by StayOne. You must leave our properties in a clean and tidy condition. You must also comply with the By-Laws that apply to the properties and shall not be guilty of conduct which is a nuisance or annoyance to adjoining or neighbouring occupiers. In the event that the property requires deep cleaning as a result of your stay, you will be charged an additional ₦250,000.00 and you forfeit your deposit. We have the right to terminate a booking at any time on the grounds of breaking the agreement within these terms or the abuse of these terms including being a nuisance to staff, StayOne subscribers or other guests, mistreatment of the property or criminal activity on the part of those occupying the apartment or their guests. No refunds are made in the event of this happening. Parties and gatherings of any kind are strictly prohibited inside and within the apartments. Any small gathering must comply with other rule regarding noise, etc
    			        </div>
    			        
    			        <div class="tandc-subhead">Indemnification & Limitation Of Liability:</div>
    			        <div class="tandc-note">
    			            You hereby indemnify, defend and hold us, our partners, subsidiaries, affiliates, franchisees and our officers, directors, agents, contractors,subcontractors, guests, StayOne subscribers, visitors, licensees, invitees, permitees and employees (collectively, the “Indemnified Parties”) harmless from and against any and all allegations, demands, claims, liabilities, damages, fines, penalties or costs of whatsoever nature (including reasonable attorneys' fees) and whether by reason of death of or injury to any person or loss of or damage to any property or otherwise (“Claims”) arising out of or in any way connected with the subscription to StayOne, the services or products provided to you by the platform or any related act or failure to act by you and whether or not occasioned or contributed to by the negligence of the Company or any agent or employee of the Indemnified Parties or any of them (except as and to the extent prohibited by applicable law). Furthermore, the company’s members, managers, agents, representatives, officers and employees, shall not at any time be liable for any special, indirect or consequential damages or any damages whatsoever, including loss of profits or data, whether in an action in contract or tort, arising out of the use or performance of the platform or the materials, or the performance or non-performance by the company or any third party providers of products or services related to this site, including but not limited to errors, mistakes, or inaccuracies of content, any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein, and any interruption or cessation of transmission to or from our site, any bugs, viruses, trojan horses, or the like, which may be transmitted to or through our website by any third party. This limitation of liability shall apply regardless of whether the claim asserted is based on contract, negligence, or any other theory of recovery. In no event shall our total liability to you for all damages, losses, and causes of action (whether in contract, tort (including, but not limited to, negligence, or otherwise) exceed the amount paid by you, if any, for accessing the site.
    			        </div>
    			        
    			        <div class="tandc-subhead">Miscellaneous</div>
    			        <div class="tandc-note">
    			            No functions, get-togethers or gatherings where occupants of neighbouring apartments might be disturbed may be conducted at the property under any circumstances unless agreed by StayOne in writing before you or your guest checks in. Exceeding the number of allowed guests will result in automatic termination of booking and you being required to vacate the property immediately without refund unless already agreed in writing by StayOne. You must leave our properties in a clean and tidy condition. You must also comply with the By Laws that apply to the properties and shall not be guilty of conduct which is a nuisance or annoyance to adjoining or neighbouring occupiers. In the event that the property requires deep cleaning as a result of your stay, you will be charged an additional ₦250,000.00 and you forfeit your deposit. We have the right to terminate a booking at any time on the grounds of breaking the agreement within these terms or the abuse of these terms including being a nuisance to staff, StayOne subscribers or other guests, mistreatment of the property or criminal activity on the part of those occupying the apartment or their guests. No refunds are made in the event of this happening. Parties and large gatherings of any kind are strictly prohibited inside and outside the apartments. Any small gathering must comply with other rule regarding noise, etc. 
                            <p>No Smoking In The Apartment, The apartment and other associated buildings are designatednonsmoking areas. There is no smoking inside any of our properties. If there is evidence of such including a smoke odour, you will be charged a fee of ₦500,000.00 to cover the cleaning of curtains and carpets and to replace items.</p>
                            <p>No Excessive Noise, Public Nuisance And Public Partying, Excessive noise is prohibited at all times and may result in eviction, loss of deposit and extra charges which may be deducted from the caution deposit. Some of the StayOne subscribers live here full–time we will appreciate if you keep noise level to a minimum. Parking indiscriminately is hereby prohibited in the estate and all traffic signs are to be strictly obeyed.</p>
                            <p>Domestic Animals:If allowed, StayOne subscribers must ensure that dogs and other domestic animals are kept within their premises. When walking their dogs, StayOne subscribers are advised to ensure that the dogs are under the care of an adult and on a leash. Pet owners must ensure that their pet faeces are immediately collected and properly disposed of. ii. All dogs or other pets allowed outside StayOne subscribers’ premises must have a means of identification, bearing the name of the animal and the owner’s name and address.</p>
                            <p>StayOne subscribers shall not to do or suffer to be done on the Property or any part thereof any act or thingwhatsoever which may be or tend to be of a nuisance, damage or unreasonable disturbance or noise to SST or other StayOne subscribers, occupants, or occupiers of any adjoining or neighboring property or at any time overcrowd the Property/premises with occupants or guests.</p>
                            <p>No Defacing Of The Apartment (Public Display, Spreading And Spraying Of Clothes And Personal Belonging/Items); Not to deface the appearance of the property in any manner whatsoever or alter or remove the SST fixtures fittings or appliances nor make or permitto be made any other alterations in or addition to the Property or any part thereof.</p>
                            <p>Property Owners and StayOne subscribers of the estate should always ensure that their surroundings are kept clean at all times. llegal kiosk(s), structures for shops, and selling points of any kind are strictly prohibited within the Estate.</p>
                            <p>Property Owners & StayOne subscriber must not allow their sewage, diesel and oil to flow into the Drainage as this may occasion environmental hazard that may cause an epidemic. Any Property Owners & StayOne subscriber violating this rule shall be surcharged for the clearing of the sewage. Violators shall also be reported to the appropriate authorities for sanction. Hawking within the Estate is strictly prohibited. Violators will be arrested and prosecuted.</p>
                            <p>On no account whatsoever are Property Owners & StayOne subscriber permitted to tamper with any public electrical equipment within the estate. All external electrical faults are to be reported to the SST Representative for immediate action and repairs.</p>
                            <p>If a member of the estate or a land owner is to transfer or alienate to anyone, the prospective vendor/tenant must be introduced to and accepted by the Estate Management and such persons must sign an undertaking to be guided by the Constitution and Rules and Regulations of the Estate.</p>
                            <p>External Contractors: In the interest of the security and safety of all StayOne subscribers of the Estate, no building contractor or any other contractor (Electricity, Plumbing, Masonry, etc.) will be allowed into the estate unless the workers are duly registered with the Secretariat and are in possession of a valid entry permit upon payment of the applicable fee.</p>
                            StayOne subscribers are enjoined to be security conscious and report any incidence of suspected crime(s) to the police or any of the Estate Security Agents. The relevant telephone numbers are obtainable at the Secretariat. In the event of an emergency, StayOne subscribers may call the Lagos State Government Emergency number: 767. Safety/Children below the age of 12(twelve) years should not be on the streets after 6.00pm unless accompanied by an adult.
    			        </div>
    			        
    			        <div class="tandc-subhead-big">Cotel Terms & Conditions</div>
    			        <div class="tandc-note">
    			            This COTEL T & C governs your use of the website for the COTEL property and reservation and is entered into by Small Small Technology Limited (“SST”) and yourself (“you”). The documents, data, information and other materials (collectively the “Material(s)”) contained on the Company’s website and platform (the “Platform”) are provided by the Company, exclusively for non-commercial, individual use by prospective and confirmed Company guests to inquire about or make reservations and related services and for no other purpose (collectively, “Authorized Users”).
                            <p>BY ACCESSING, USING, VIEWING, TRANSMITTING, CACHING OR STORING THIS SITE OR ANY OF ITS SERVICES, FUNCTIONS, MATERIALS, OR CONTENTS, YOU SHALL BE DEEMED TO HAVE AGREED TO EACH AND ALL THE TERMS, CONDITIONS, AND NOTICES IN THIS AGREEMENT WITHOUT MODIFICATION. If you are not an Authorized User, and if you do not agree to the terms of this Agreement, you may not use this Site or download any Materials from it.</p>
                            The Company, in its sole and absolute discretion, reserves the right to change the terms, conditions, and notices under which the Materials and the Site are offered at any time without notice and, unless otherwise indicated, such changes will become effective immediately; therefore, please check these terms periodically for changes. Your continued use of the Site following the posting of changes to this Agreement will mean you accept those changes.

    			        </div>
    			        
    			        <div class="tandc-subhead">Reservation Policy and Payment</div>
    			        <div class="tandc-note">
    			            For any reservation to be valid, reservation can only be held for 48 hours; after which it is cancelled automatically. A deposit of 50% of the total accommodation bill shall be required to make a valid reservation. A coteller may cancel with sufficient notice. Payments must be made before check – in Failure to pay prescribed fees/dues as at when due will attract penalties such as cessation or refusal of service delivery to coteller where applicable. In addition, any other privilege associated with residing in the Cotel may be withdrawn from any coteller who fails to meet his/her financial obligations.
    			        </div>
    			        
    			        <div class="tandc-subhead">Cancellation and change of booking date </div>
    			        <div class="tandc-note">
    			            Any cancellation or modification of a booking can only be effected by the coteller providing a written notification of the cancellation or modification to COTEL. The non-payment of rental balances results in automatic cancellation. Should the Guest for whatever reason cancel the booking, they will have the right to reimbursement of all money paid subject to the deduction of cancellation charges being 30% of the total rental price if cancellation is made 7 days prior to the guest checking in. Changes to booking dates or properties are subject to availability. Each booking change shall incur a service fee of 10% to be paid at the time of confirming the said changes. If we cancel a confirmed booking, we shall do our utmost to find a replacement property acceptable to the Guest, or refund any monies paid on unused rental. The Guest agrees and acknowledges that in this event, COTEL liability for damages will be limited to the amount of unused rental, based on a pro rata calculation of unused rental days. Should a property become unserviceable prior to the arrival of a Guest, We will do our best to find a suitable replacement property of an equal standard. In the event of a more expensive property being selected, the Guest will have the choice of paying the difference or receiving a full refund of monies paid. Cancellations cannot be made once the guest has checked-in and all booking payments are non-refundable after the guest has checked-in.
    			        </div>
    			        
    			        <div class="tandc-subhead">Check- in and Check Out</div>
    			        <div class="tandc-note">
    			            All properties are usually available for occupation after 12:00 noon on the day of arrival. All properties must be vacated by 12:00 noon on the day of departure. If there is any delay in vacating the property beyond the agreed time a full day’s rental is charged to you.  Please hand over key to the steward on duty when checking
    			        </div>
    			        
    			        <div class="tandc-subhead">Security Deposit and Property Damage</div>
    			        <div class="tandc-note">
    			            All security deposits are fully refundable PROVIDED there are no damages to the booked COTEL property by you or your associates. A 50% security deposit must be paid before check – in. In the event that a guest damages an item, multiple items or damages the property, a guest forfeits the caution or security deposit paid and the guest is liable to cover cost of up to ₦500,000 damages equating to the cost of replacing the damaged item(s) or damaged property as stipulated by COTEL. The security deposit shall be refunded within 72hrs of you or your guest’s departure. We have the authority to withhold or deduct monies from the security deposit or credit card to remedy any damage, excess cleaning, missing items, excess utilities caused by the Guest or to send an invoice for such monies to the Guest by email for immediate payment. You may not remove any of the furniture or effects from the properties and will be liable for any furniture or effects damaged or missing from the properties. Furniture must be returned to its original position. Our representatives and subcontractors have the right of access to the property at any time, with due regard to your convenience, for the purpose of inspection of the properties and to carry out any essential repair or maintenance work.
    			        </div>
    			        
    			        <div class="tandc-subhead">No Unaccredited Visitor/Guest On The Property</div>
    			        <div class="tandc-note">
    			            All accommodation must only be used for private/residential use only. No guests are allowed within the residential area, rooms or common areas without the express notification of the COTEL management and approval in writing before you or your guests check in. No functions, get-togethers or gatherings where occupants of neighbouring apartments might be disturbed may be conducted at the property under any circumstances unless agreed by COTEL in writing before such an event or function. Admission of guests without approval will result in automatic termination of booking and you being required to vacate the property immediately without refund unless already agreed in writing by COTEL. You must leave our properties in a clean and tidy condition. You must also comply with the By-Laws that apply to the properties and shall not be guilty of conduct which is a nuisance or annoyance to adjoining or neighbouring occupiers. In the event that the property requires deep cleaning as a result of your stay, you will be charged an additional ₦250,000.00 and you forfeit your deposit.  We have the right to terminate a booking at any time on the grounds of breaking the agreement within these terms or the abuse of these terms including being a nuisance to staff, cotellers or other guests, mistreatment of the property or criminal activity on the part of those occupying the apartment or their guests. No refunds are made in the event of this happening.  Parties and gatherings of any kind are strictly prohibited inside and within the apartments. Any small gathering must comply with other rule regarding noise, etc
    			        </div>
    			        
    			        <div class="tandc-subhead">Indemnification & Limitation Of Liability</div>
    			        <div class="tandc-note">
    			            You hereby indemnify, defend and hold us, our partners, subsidiaries, affiliates, franchisees and our officers, directors, agents, contractors, subcontractors, guests, cotellers, visitors, licensees, invitees, permitees and employees (collectively, the “Indemnified Parties”) harmless from and against any and all allegations, demands, claims, liabilities, damages, fines, penalties or costs of whatsoever nature (including reasonable attorneys' fees) and whether by reason of death of or injury to any person or loss of or damage to any property or otherwise (“Claims”) arising out of or in any way connected with the subscription to COTEL, the services or products provided to you by the platform or any related act or failure to act by you and whether or not occasioned or contributed to by the negligence of the Company or any agent or employee of the Indemnified Parties or any of them (except as and to the extent prohibited by applicable law). Furthermore, the company’s members, managers, agents, representatives, officers and employees, shall not at any time be liable for any special, indirect or consequential damages or any damages whatsoever, including loss of profits or data, whether in an action in contract or tort, arising out of the use or performance of the platform or the materials, or the performance or non-performance by the company or any third party providers of products or services related to this site, including but not limited to errors, mistakes, or inaccuracies of content, any unauthorized access to or use of our secure servers and/or any and all personal information and/or financial information stored therein, and any interruption or cessation of transmission to or from our site, any bugs, viruses, trojan horses, or the like, which may be transmitted to or through our website by any third party. This limitation of liability shall apply regardless of whether the claim asserted is based on contract, negligence, or any other theory of recovery. In no event shall our total liability to you for all damages, losses, and causes of action (whether in contract, tort (including, but not limited to, negligence, or otherwise) exceed the amount paid by you, if any, for accessing the site. 
    			        </div>
    			        
    			        <div class="tandc-subhead">Miscellaneous </div>
    			        <div class="tandc-note">
    			            No functions, get-togethers or gatherings where occupants of neighbouring apartments might be disturbed may be conducted at the property under any circumstances unless agreed by COTEL in writing before you or your guest checks in. Exceeding the number of allowed guests will result in automatic termination of booking and you being required to vacate the property immediately without refund unless already agreed in writing by COTEL. You must leave our properties in a clean and tidy condition. You must also comply with the By Laws that apply to the properties and shall not be guilty of conduct which is a nuisance or annoyance to adjoining or neighbouring occupiers. In the event that the property requires deep cleaning as a result of your stay, you will be charged an additional ₦250,000.00 and you forfeit your deposit. We have the right to terminate a booking at any time on the grounds of breaking the agreement within these terms or the abuse of these terms including being a nuisance to staff, cotellers or other guests, mistreatment of the property or criminal activity on the part of those occupying the apartment or their guests. No refunds are made in the event of this happening. Parties and large gatherings of any kind are strictly prohibited inside and outside the apartments. Any small gathering must comply with other rule regarding noise, etc.
                            <p>No Smoking In The Apartment, The apartment and other associated buildings are designated nonsmoking areas. There is no smoking inside any of our properties. If there is evidence of such including a smoke odour, you will be charged a fee of ₦500,000.00 to cover the cleaning of curtains and carpets and to replace items.</p>
                            <p>No Excessive Noise, Public Nuisance And Public Partying, Excessive noise is prohibited at all times and may result in eviction, loss of deposit and extra charges which may be deducted from the caution deposit. Some of the cotellers live here full – time we will appreciate if you keep noise level to a minimum. Parking indiscriminately is hereby prohibited in the estate and all traffic signs are to be strictly obeyed.</p>
                            <p>Domestic Animals: If allowed, Cotellers must ensure that dogs and other domestic animals are kept within their premises. When walking their dogs, cotellers are advised to ensure that the dogs are under the care of an adult and on a leash. Pet owners must ensure that their pet faeces are immediately collected and properly disposed of. ii. All dogs or other pets allowed outside cotellers’ premises must have a means of identification, bearing the name of the animal and the owner’s name and address.</p>
                            <p>Cotellers are enjoined to be security conscious and report any incidence of suspected crime(s) to the police or any of the Estate Security Agents. The relevant telephone numbers are obtainable at the Secretariat. In the event of an emergency, cotellers may call the Lagos State Government Emergency number: 767. Safety/ Conduct of Children i. Children below the age of 12(twelve) years should not be on the streets after 6.00pm unless accompanied by an adult.</p>
                            <p>Cotellers shall not to do or suffer to be done on the Property or any part thereof any act or thing whatsoever which may be or tend to be of a nuisance, damage or unreasonable disturbance or noise to SST or other cotellers, occupants, or occupiers of any adjoining or neighboring property or at any time overcrowd the Property/premises with occupants or guests.</p>
                            No Defacing Of The Apartment (Public Display, Spreading And Spraying Of Clothes And Personal Belonging/Items); Not to deface the appearance of the property in any manner whatsoever or alter or remove the SST fixtures fittings or appliances nor make or permit to be made any other alterations in or addition to the Property or any part thereof

    			        </div>
    			    </div>
    			</div>
    			<!--- Section ends here --->
			</div>
			
	<script src="<?php echo base_url('assets/js/faq.js'); ?>"></script>	
			